# Generated by Django 3.2.4 on 2021-07-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentbe', '0002_tournament_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField()),
                ('firstTeamScore', models.PositiveIntegerField(null=True)),
                ('secondTeamScore', models.PositiveIntegerField(null=True)),
                ('played', models.BooleanField(default=False)),
                ('firstTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstTeam', to='tournamentbe.team')),
                ('secondTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondTeam', to='tournamentbe.team')),
            ],
        ),
    ]
