# Generated by Django 3.2.4 on 2021-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentbe', '0003_auto_20210701_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='firstTeamScore',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondTeamScore',
            field=models.PositiveIntegerField(),
        ),
    ]
