# Generated by Django 3.2.4 on 2021-07-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentbe', '0005_auto_20210701_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_column='name', max_length=40),
        ),
    ]
